# Generated by Django 3.2.4 on 2021-07-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0005_myuser_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='myUser',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
